version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    groups:
      MSTest:
        patterns:
          - "MSTest.*"
    schedule:
      interval: monthly
    open-pull-requests-limit: 20

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 20
