name: Test dotnet-test-split
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
            dotnet-version: '3.1.x'

      - name: Prepare test assets
        run: dotnet test --logger "trx;LogFileName=../../reports/mstest-report.trx" TestAssetsMstest/TestAssetsMstest.csproj || exit 0
      - name: Split tests assets
        run: |
          dotnet build
          cd DotnetTestSplit/bin/Debug/netcoreapp3.1 && ls -la && ./DotnetTestSplit ../../../../reports/mstest-report.trx
      - name: Run test
        run: dotnet test --logger "trx;LogFileName=../../reports/dotnet-test-split-report.trx" TestDotnetTestSplit/TestDotnetTestSplit.csproj

      - name: Publish test report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: test-report
          path: reports/dotnet-test-split-report.trx
          reporter: dotnet-trx
          fail-on-error: 'true'

      - name: Generate junit html reports
        if: always()
        run: ant report
      - name: Publish test report files
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test report files
          path: |
            expected
            reports
